# Generated by Django 5.0.7 on 2024-07-12 08:32

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='goods/images')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('producer', models.CharField(choices=[('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Microsoft', 'Microsoft'), ('LG', 'LG'), ('Gigabyte', 'Gigabyte'), ('HP', 'HP'), ('Razer', 'Razer'), ('MSI', 'MSI'), ('Samsyng', 'Samsung'), ('Huawei', 'Huavei'), ('Xiaomi', 'Xiaomi')], default=' ', max_length=100)),
                ('screen_diagonal', models.CharField(choices=[('12.9" and less', '12.9" and less'), ('13"', '13"'), ('13.3"', '13.3"'), ('13.4"', '13.4"'), ('13.6"', '13.6"'), ('13.9"', '13.9"'), ('14"', '14"'), ('14.1"', '14.1"'), ('14.4"', '14.4"'), ('14.5"', '14.5"'), ('15"', '15"'), ('15.4"', '15.4"'), ('15.5"', '15.5"'), ('15.6"', '15.6"'), ('15.7"', '15.7"'), ('16"', '16"'), ('16.1"', '16.1"'), ('16.4"', '16.4"'), ('17"', '17"'), ('17.1"', '17.1"'), ('17.3"', '17.3"'), ('17.4"', '17.4"'), ('17.6"', '17.6"'), ('18" and more', '18" and more')], default=' ', max_length=40)),
                ('screen_coating', models.CharField(choices=[('Mates', 'Mates'), ('Glossy', 'Glossy')], default=' ', max_length=40)),
                ('in_stock', models.BooleanField(default=True)),
                ('screen_resolution', models.CharField(choices=[('1920 x 1080', '1920 x 1080'), ('2560 x 1440', '2560 x 1440'), ('2560 x 1600', '2560 x 1600'), ('3840 x 2160', '3840 x 2160'), ('3200 x 2000', '3200 x 2000'), ('3072 x 1920', '3072 x 1920'), ('2880 x 1800', '2880 x 1800'), ('3840 x 2400', '3840 x 2400'), ('1920 x 1200', '1920 x 1200')], default=' ', max_length=40)),
                ('touchscreen', models.BooleanField(default=False)),
                ('processor', models.CharField(choices=[('Intel Core i9', 'Intel Core i9'), ('Intel Core i7', 'Intel Core i7'), ('Intel Core i5', 'Intel Core i5'), ('Intel Core i3', 'Intel Core i3'), ('Intel Pentium', 'Intel Pentium'), ('Intel Celeron', 'Intel Celeron'), ('Intel N-series', 'Intel N-series'), ('AMD Ryzen 9', 'AMD Ryzen 9'), ('AMD Ryzen 7', 'AMD Ryzen 7'), ('AMD Ryzen 5', 'AMD Ryzen 5'), ('AMD Ryzen 3', 'AMD Ryzen 3'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('Other', 'Other')], default=' ', max_length=60)),
                ('number_of_processor_cores', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('24', '24')], default=' ', max_length=40)),
                ('ram', models.CharField(choices=[('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64'), ('64', '64'), ('128', '128'), ('More than 128', 'More than 128')], default=' ', max_length=60)),
                ('ssd_scope', models.CharField(choices=[('120 GB and less', '120 GB and less'), ('128 GB', '128 GB'), ('130 GB', '130 GB'), ('130-250 GB', '130-250 GB'), ('256 GB', '256 GB'), ('260-479 GB', '260-479 GB'), ('480 GB', '480 GB'), ('500 GB', '500 GB'), ('512 GB', '512 GB'), ('640 GB', '640 GB'), ('750 GB', '750 GB'), ('768 GB', '768 GB'), ('960 GB', '960 GB'), ('1 TB', '1 TB'), ('2 TB and more', '2 TB and more')], default=' ', max_length=70)),
                ('video_card_type', models.CharField(choices=[('Integrated', 'Integrated'), ('Discrete', 'Discrete')], default=' ', max_length=50)),
                ('keyboard_backlighting', models.BooleanField(default=True)),
                ('os', models.CharField(choices=[('Linux', 'Linux'), ('Windows 10 Home', 'Windows 10 Home'), ('Windows 11 Home', 'Windows 11 Home'), ('Windows 11 Pro Education', 'Windows 11 Pro Education'), ('Windows 11 Professional', 'Windows 11 Professional'), ('Windows 7/8 Home', 'Windows 7/8 Home'), ('Windows 7/8 Professional', 'Windows 7/8 Professional'), ('Mac OS', 'Mac OS'), ('Without OS', 'Without OS')], default=' ', max_length=100)),
                ('additionally', multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Fingerprint identification', 'Fingerprint identification'), ('3G/4G/5G module', '3G/4G/5G module'), ('With Ukrainian layout', 'With Ukrainian layout'), ('With optical drive', 'With optical drive'), ('With backlit keyboard', 'With backlit keyboard'), ('With touch screen', 'With touch screen'), ('Charging from USB', 'Charging from USB'), ('Thunderbolt port', 'Thunderbolt port'), ('Counter-impact housing', 'Counter-impact housing'), ('Supports connection of 2 monitors', 'Supports connection of 2 monitors'), ('With graphic docking station', 'With graphic docking station'), ('Removable battery', 'Removable battery')], default=' ', max_length=267)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('White', 'White'), ('Red', 'Red'), ('Dark gray', 'Dark gray'), ('White/black', 'White/black'), ('Gray/black', 'Gray/black'), ('Silver/black', 'Silver/black')], default=' ', max_length=100)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
    ]
