# Generated by Django 5.0.7 on 2024-07-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ram',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64'), ('128', '128'), ('More than 128', 'More than 128')], default=' ', max_length=60),
        ),
    ]
